server:  
  port: ${PORT:8761}

spring:
  application:
    name: discovery-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    
eureka:  
  instance:
    hostname: discovery-service
    #    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false

